name: Go Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    container:
      image: debian:latest # Use a Debian base image
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies for rr and testing
      run: |
        apt-get update
        apt-get install -y wget

    - name: Download and install rr
      run: |
        wget https://github.com/rr-debugger/rr/releases/download/5.9.0/rr-5.9.0-Linux-x86_64.deb
        dpkg -i rr-5.9.0-Linux-x86_64.deb

    - name: Install Go dependencies
      run: go mod download

    - name: Run unit tests with rr
      run: rr record go test -v ./... -short

    - name: Upload rr trace artifact
      uses: actions/upload-artifact@v4
      if: always() # Always run this step, even if tests fail, to get the trace
      with:
        name: rr-trace
        path: ~/.local/share/rr/latest-trace
        retention-days: 7 # Optional: How long to keep the artifact 